[package]
name = "elastic-balls-2d"
version = "0.1.0"
edition = "2021"
description = "Simulate and visualize elastic collisions of multiple balls in 2D space"

[dependencies]
macroquad = "0.4"
rand = "0.8"
