project:
  type: website
  pre-render: scripts/update-last-modified.sh
  post-render: scripts/restore-last-modified.sh

website:
  title: "Introduction to Coding Agents"
  navbar:
    left:
      - href: slides/slide.qmd
        text: slide

format:
  html:
    theme:
      light: cosmo
      dark: cyborg
    # css: styles.css
    toc: true
