project:
  type: website

website:
  title: "Introduction to Coding Agents"
  navbar:
    left:
      - href: slides/slide.qmd
        text: slide

format:
  html:
    theme:
      light: cosmo
      dark: cyborg
    # css: styles.css
    toc: true
