project:
  type: website

website:
  title: "Quarto slide example"
  navbar:
    left:
      - href: slide/slide.qmd
        text: slide

format:
  html:
    theme: cosmo
    # css: styles.css
    toc: true