name = "ElasticBalls2D"
uuid = "a1e11ffc-b2a8-4196-bf9f-8675be0ac5c6"
version = "0.1.0"
authors = ["SatoshiTerasaki <terasakisatoshi.math@gmail.com>"]

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
CairoMakie = "0.15.8"
Colors = "0.13.1"
Makie = "0.24.8"
StaticArrays = "1.9.16"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
