name = "ElasticBalls"
uuid = "3728bc42-0042-498a-b2c7-5ff85938c383"
version = "0.1.0"
authors = ["SatoshiTerasaki <terasakisatoshi.math@gmail.com>"]

[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
ImageIO = "82e4d734-157c-48bb-816b-45c225c6df19"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Luxor = "ae8d54c2-7ccd-5906-9d76-62fc9837b5bc"

[compat]
Colors = "0.13.1"
FileIO = "1.18.0"
ImageIO = "0.6.9"
Images = "0.26.2"
LinearAlgebra = "1.12.0"
Luxor = "4.4.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
