name = "ElasticCollisions"
uuid = "d62925eb-fca4-42ed-a3e4-c498286cb13d"
version = "0.1.0"
authors = ["Satoshi Terasaki <terasakisatoshi.math@gmail.com>"]

[deps]
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
ColorTypes = "0.12.1"
LinearAlgebra = "1.12.0"
Plots = "1.41.6"
StaticArrays = "1.9.16"
